""" add social login 

Revision ID: 2e6be1934891
Revises: b37160862ba6
Create Date: 2024-11-28 19:16:19.108720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6be1934891'
down_revision = 'b37160862ba6'
branch_labels = None
depends_on = None



def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(120), nullable=True))
        batch_op.add_column(sa.Column('social_id', sa.String(64), nullable=True))
        batch_op.add_column(sa.Column('social_provider', sa.String(20), nullable=True))
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_social_id', ['social_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('is_guest')
        batch_op.drop_column('social_provider')
        batch_op.drop_column('social_id')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
