"""Add SMS and working hours fields to User model

Revision ID: 4c02f4b82b87
Revises: af7a58e91709
Create Date: 2024-11-15 22:02:03.797742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c02f4b82b87'
down_revision = 'af7a58e91709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vacation_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('working_hours_start', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('working_hours_end', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('working_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('off_hours_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vacation_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vacation_message')
        batch_op.drop_column('off_hours_message')
        batch_op.drop_column('working_days')
        batch_op.drop_column('working_hours_end')
        batch_op.drop_column('working_hours_start')
        batch_op.drop_column('vacation_mode')
        batch_op.drop_column('sms_enabled')

    # ### end Alembic commands ###
