"""Add is_admin column

Revision ID: 734f5863c01a
Revises: d19232ca9b1c
Create Date: 2024-11-16 21:47:52.925740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f5863c01a'
down_revision = 'd19232ca9b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
