"""Add admin functionality models

Revision ID: 986e0930d86d
Revises: 734f5863c01a
Create Date: 2024-11-16 22:08:37.691333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986e0930d86d'
down_revision = '734f5863c01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('monthly_sms_limit', sa.Integer(), nullable=True),
    sa.Column('sms_sent_this_month', sa.Integer(), nullable=True),
    sa.Column('reset_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quota')
    op.drop_table('user_activity')
    # ### end Alembic commands ###
