"""add name

Revision ID: b37160862ba6
Revises: ab126e94ba55
Create Date: 2024-11-26 20:30:44.759396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37160862ba6'
down_revision = 'ab126e94ba55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.drop_column('certifications')
        batch_op.drop_column('education')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.TEXT(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
