"""Add requested_specialists to Case model

Revision ID: c67659efd9e3
Revises: 29f9000ff6ae
Create Date: 2024-11-24 00:22:21.695578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67659efd9e3'
down_revision = '29f9000ff6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_specialists', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('requested_specialists')

    # ### end Alembic commands ###
