""" add accepted_at field to case model

Revision ID: d0f3d60c20ab
Revises: 00ea3a634232
Create Date: 2024-12-07 20:48:28.957252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f3d60c20ab'
down_revision = '00ea3a634232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('accepted_at')

    # ### end Alembic commands ###
