"""Add SMS template fields

Revision ID: d19232ca9b1c
Revises: 4c02f4b82b87
Create Date: 2024-11-16 01:02:23.014871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19232ca9b1c'
down_revision = '4c02f4b82b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_template', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sms_template')

    # ### end Alembic commands ###
